# Site settings
title: "Apurva's Webshop"
description: "This is my personal webshop showcasing my projects and work."
baseurl: "" # Leave empty for GitHub Pages
url: "https://yourusername.github.io" # Your GitHub Pages URL

# GitHub Pages theme
remote_theme: "pages-themes/architect@v0.2.0"

# Plugins for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Optional settings for SEO
author: "Apurva Sharma"
email: "your-email@example.com" # Optional, for contact info
social_links:
  linkedin: "https://www.linkedin.com/in/apurva-sharma-b4a4a8207/"

# Exclude files and folders
exclude:
  - Gemfile
  - Gemfile.lock

# Markdown and Highlighter
markdown: kramdown
highlighter: rouge
